"""App utilities package exposing common helpers."""

from app.utils.common import (
    get_app_dir,
    get_cache_dir,
    get_logs_dir,
    get_assets_dir,
    get_projects_dir,
    ensure_dir,
    sanitize_filename,
    purge_directory,
    safe_read_text,
    safe_write_text,
    safe_read_json,
    safe_write_json,
    optimize_image_for_ai,
    image_bytes_to_base64,
    image_file_to_base64_data_uri,
    strip_thought_content,
    clean_latex_math,
    compute_file_sha256,
    compute_bytes_sha256,
    compute_text_sha256,
    get_logger,
)

__all__ = [
    "get_app_dir",
    "get_cache_dir",
    "get_logs_dir",
    "get_assets_dir",
    "get_projects_dir",
    "ensure_dir",
    "sanitize_filename",
    "purge_directory",
    "safe_read_text",
    "safe_write_text",
    "safe_read_json",
    "safe_write_json",
    "optimize_image_for_ai",
    "image_bytes_to_base64",
    "image_file_to_base64_data_uri",
    "strip_thought_content",
    "clean_latex_math",
    "compute_file_sha256",
    "compute_bytes_sha256",
    "compute_text_sha256",
    "get_logger",
]
