"""Utility for stripping AI internal thinking/reasoning blocks (<think>, <thought>, etc.) from responses."""

import re

def strip_thought_content(text: str) -> str:
    """
    Strips internal thoughts and reasoning traces generated by models like DeepSeek-R1,
    Qwen-Thinking, Claude, or Gemini Thinking before presenting to the user.
    """
    if not text:
        return ""

    res = text

    # 1. Standard closed XML-style think/thought tags: <think>...</think>, <thought>...</thought>
    res = re.sub(r"<(think|thought)>[\s\S]*?</\1>", "", res, flags=re.IGNORECASE)

    # 2. Unclosed think/thought tags (e.g. if generation cut off midway through thought)
    res = re.sub(r"<(think|thought)>[\s\S]*$", "", res, flags=re.IGNORECASE)

    # 3. Fenced thought blocks: ```thought ... ``` or ```think ... ```
    res = re.sub(r"```(thought|think)[\s\S]*?```", "", res, flags=re.IGNORECASE)

    # 4. Leading Thinking Process / Thought blocks
    res = re.sub(r"^\s*(\*+)?(Thinking Process|Reasoning Process|Thought):?(\*+)?[\s\S]*?\n\n", "", res, flags=re.IGNORECASE)

    # 5. Bracketed thinking: [Thinking: ...]
    res = re.sub(r"\[(Thinking|Thought|Reasoning):[\s\S]*?\]", "", res, flags=re.IGNORECASE)

    return res.strip()
